### ISSUE TITLE
5. マネジメントコンソールの構成

### ISSUE THREAD

**Issue by shigeru-oda** [otanikohei/How_to_Sign_up_AWS_Account#2]
1.提案です
現在：サポートセンター へのリンクや、AWS IQ というエキスパートとコンタクトを取るためのツール、re:Post という**新しい**フォーラムなどにアクセスができます。
修正：サポートセンター へのリンクや、AWS IQ というエキスパートとコンタクトを取るためのツール、re:Post というフォーラムなどにアクセスができます。

ご新規様が使う資料なので、新しい、古いの情報は無くても良きかなと思った次第です。

2.リージョンの説明が欲しいと思いました。
WordPressのハンズオン資料を転用します？

**Comment by otanikohei** [comment]
re:Post に関する詳細を記載してないため、新旧の記載は不要と感じました。
re:Post の部分修正しました。

リージョンの説明文を追加しました。

**Comment by shigeru-oda** [comment]
OK
