### ISSUE TITLE
6. セキュリティ強化 - MFA

### ISSUE THREAD

**Issue by shigeru-oda** [otanikohei/How_to_Sign_up_AWS_Account#3]
・誤記
✖︎：セキュリティ認証情報 の画面に遷移するので、[ 多要素認証 (**MDA**) ] にあります [ MFA の有効化 ] ボタンをクリックしてください。
●：セキュリティ認証情報 の画面に遷移するので、[ 多要素認証 (**MFA**) ] にあります [ MFA の有効化 ] ボタンをクリックしてください。

**Comment by otanikohei** [comment]
よく気づかれました！ありがとうございます。タイポのため修正しました。

**Comment by shigeru-oda** [comment]
OK
