### ISSUE TITLE
ドライランFB

### ISSUE THREAD

**Issue by mi-kobaaa** [otanikohei/How_to_Sign_up_AWS_Account#6]
お忙しい中作成ありがとうございます、初心者支部小林です！
ドライランをしてみて、いくつか気になった点がありましたので共有します。

### 手順9 IAMユーザーでサインインする
- IAMユーザーの初回ログイン時にパスワード変更画面が出ますので、口頭でもフォローがあったほうが良いと思いました。

### 手順10 CloudTrail
- 初めてCloudTrailを有効化する場合、クイック証跡という画面が出てS3バケットの変更ができません。![image](https://user-images.githubusercontent.com/69611246/188297125-2cac113e-ec29-4b6d-8bd4-e3d62325e4ed.png)
    - そのため左メニュー => 証跡 => 証跡の作成という手順で設定をした方が良さそうです。![image](https://user-images.githubusercontent.com/69611246/188297154-1afb241c-0958-4242-be7b-0d7b2fc2c222.png)

- 硝石の作成でSSE-KMSを有効化する場合、エイリアスの設定が必要ですのでフォローがあった方が良さそうです。
![image](https://user-images.githubusercontent.com/69611246/188297209-34a471db-1a37-416c-ae02-27b131f45e6b.png)

わかりづらいところがあればMessengerでもDMでもこのスレッドでもご連絡ください！

**Comment by otanikohei** [comment]
> 手順9 IAMユーザーでサインインする
ありがとうございます。一文を追加しました。

> 初めてCloudTrailを有効化する場合、クイック証跡という画面が出て
これは、綺麗なアカウントで試せておらず失礼しました。
また、画像まで大変ありがたいです。追加しました。

> 証跡の作成でSSE-KMS
こちらは他でも指摘があり、無効化することにしました。
